[package]
name = "aoc2019"
version = "0.1.0"
authors = ["HTune <atune313@gmail.com>"]
edition = "2018"

[dependencies]
num = "0.2.0"
num-bigint = "0.2.3"
num-traits = "0.2.10"
err-derive = "0.2.1"
itertools = "0.8.2"
log = "0.4.8"
